### ISSUE TITLE
User guide out of date?

### ISSUE THREAD

**Issue by Cassolotl** [fallerOfFalls/AutismChat4#15]
Hello!

The user guide linked from [here](https://github.com/fallerOfFalls/AutismChat4) is [this one](https://docs.google.com/document/d/1IBBq-ru-qQn3SEVy5342BEs_77vo94biNJ3_XFtjFyM/edit?usp=sharing), which is called AutismChat 3.0 User Guide, which is not 4.

Is it up to date and reflective of AutismChat 4's functionality?

**Comment by fallerOfFalls** [comment]
Yeah, I haven't written the user guide for AutismChat 4 yet.

I've fixed the link so it points to the new document.

**Comment by fallerOfFalls** [comment]
Okay, I've edited it to reflect autismchat 4 functionality. Not super happy with it, but good enough for now, I think. Probably want to move away from google docs to ghost blog at some point.

**Comment by Cassolotl** [comment]
Thanks. :)
