### ISSUE TITLE
You CAN join a party while red

### ISSUE THREAD

**Issue by fallerOfFalls** [fallerOfFalls/AutismChat4#3]
If you are in a red party and you join a player who is in a party that you would be able to join if you were white, you successfully join it, and become the colour of that party.

**Comment by RichardB122** [comment]
This issue is resolved and can be closed, correct?

**Comment by fallerOfFalls** [comment]
just tested. did successfully join the party, but didn't change the colour of that party (red while in a party!). so no not quite.
